/*  File generated by: Map Ed v0.98.5 */


#ifndef __WORLD1LEVEL1_H__
#define __WORLD1LEVEL1_H__

#define World1Level1MapWidth = 424

extern const unsigned short World1Level1Palette[16];
extern const unsigned short World1Level1Tiles[816];
extern const unsigned short World1Level1Map[13568];
extern const unsigned short World1Level1Collision[13568];
#endif // __WORLD1LEVEL1_H__