/*  File generated by: Map Ed v0.98.5 */

#ifndef __WORLD1LEVEL2_H__
#define __WORLD1LEVEL2_H__

extern const unsigned short World1Level2Palette[16];
extern const unsigned short World1Level2Tiles[816];
extern const unsigned short World1Level2Map[13568];
extern const unsigned short World1Level2Collision[13568];

#endif