/*  File generated by: Map Ed v0.98.5 */


#ifndef __WORLD1MAP_H__
#define __WORLD1MAP_H__
extern const unsigned short World1MapPalette[256];
extern const unsigned short World1MapMap[1024];
extern const unsigned short World1MapCollision[1024];

extern const unsigned short World1MapTilesA[1024];
extern const unsigned short World1MapTilesB[1024];
extern const unsigned short World1MapTilesC[1024];
extern const unsigned short World1MapTilesD[1024];

#endif // __WORLD1MAP_H__